### ISSUE TITLE
Can't generate true random uuids. I get allways the same 

### ISSUE THREAD

**Issue by Rallex** [RobTillaart/UUID#6] opened 2022-06-29 00:15 UTC
I  have tried to reseed the random generator, but I get the same sequences of UUIDs. What I´m doing wrong?
Regards
this is the result:
________

```
19:13:41.602 -> UUID_performance.ino
19:13:41.648 -> UUID_LIB_VERSION: 0.1.3
19:13:42.632 -> UUID: 08476dee-80a7-bb4c-f727-e2fe433a9177
19:13:42.678 -> 16808
19:13:42.678 -> 23710
19:13:44.640 -> UUID: 023b7641-a48d-f2cb-2540-208180101ca6
19:13:44.687 -> 28234
19:13:44.687 -> 33173
19:13:46.651 -> UUID: 0322cbbb-d80e-a415-373c-b6b0c93c4913
19:13:46.651 -> 16359
19:13:46.698 -> 4823
19:13:48.944 -> 
19:13:48.944 -> UUID_performance.ino
19:13:48.944 -> UUID_LIB_VERSION: 0.1.3
19:13:49.921 -> UUID: 08476dee-80a7-bb4c-f727-e2fe433a9177
19:13:49.968 -> 16808
19:13:49.968 -> 23710
19:13:51.933 -> UUID: 023b7641-a48d-f2cb-2540-208180101ca6
19:13:51.981 -> 28234
19:13:51.981 -> 33173
19:13:53.946 -> UUID: 0322cbbb-d80e-a415-373c-b6b0c93c4913
```
----------------

This is the sketch

```cpp
//
//    FILE: UUID_performance.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: demo

#include "Arduino.h"
#include "UUID.h"

UUID uuid;

void setup()
{
  Serial.begin(9600);
  while (!Serial);

  Serial.println();
  Serial.println("UUID_performance.ino");
  Serial.print("UUID_LIB_VERSION: ");
  Serial.println(UUID_LIB_VERSION);
}


void loop()
{
  uuid.setRandomMode();
unsigned int s1 = random(1,65535);
unsigned int s2 = random(1,65535);
    uuid.seed(s1,s2);
  delay(1000);
    
    uuid.generate();
  Serial.print("UUID: ");
  Serial.println(uuid);
  Serial.println(s1);
  Serial.println(s2);
  delay(1000);
}


// -- END OF FILE --
```

**Comment by RobTillaart** [comment] 2022-06-29 03:31
Thanks for this issue, I will investigate it asap.

**Comment by RobTillaart** [comment] 2022-06-29 03:42
Can you try to seed it with the following code
```cpp
s1 = analogRead(A0);
```
If the A0 line is floating it might give some random values.

The problem seems to be the Arduino **random()** function. This repeats the same sequence over and over. 

True random numbers need external random events. A way to generate them (relative good ones)  is to measure timing in micros of 8 inputs over serial. Use only the last byte and construct 2 uint32_t s1 and s2 from it by shifting and xor or so.

Will write an example later.

**Comment by RobTillaart** [comment] 2022-06-29 03:45
Sorry hit the close by accident.

**Comment by RobTillaart** [comment] 2022-06-29 07:04
Added example - https://github.com/RobTillaart/UUID/tree/master/examples/UUID_random_seed

The function **extractEntropy()** extract randomness from two sources.

#### compile time constants 
```__DATE__  __TIME__ and __FILE__```
you can extend this with other constants e.g. board info, compiler version whatever.
this part will generate a new random seed every time you compile the code.

#### run time events, 
In this case pressing the send button 8 times.
You might replace this part with other forms of runtime randomness e.g. noise of a sensor whatever 

#### code
The code does XOR, SHIFT and MUL to spread the entropy over the whole uint32_t.

disclaimer, this is not mathematically tested and verified "true random" code.

**Comment by RobTillaart** [comment] 2022-07-02 08:44
@Rallex 
Is your problem solved now?

**Comment by RobTillaart** [comment] 2022-07-04 10:15
As there is no answer I assume the problem is solved so I close the issue.
If not solved, feel free to reopen the issue.

**Comment by Rallex** [comment] 2022-07-04 14:47
Hi,  
This works well, but I need to send 8 characters. 
I would like it to work without sending codes
Thanks for your dedication
Regards

**Comment by RobTillaart** [comment] 2022-07-04 15:31
> This works well, but I need to send 8 characters.
I would like it to work without sending codes

What does 8 characters have to do with UUID?
Or the randomness of the UUID?
I do not understand what you mean with **sending codes**

**Comment by Rallex** [comment] 2022-07-04 15:39
I mean this code


  // GET RUNTIME ENTROPY
  Serial.println("send 8 chars");
  uint32_t mask = 0;
  for (int i = 0; i < 8; i++)
  {
    while (Serial.available() == 0);
    if (Serial.available())
    {
      mask <<= 7;
      mask ^= micros();
      Serial.read();
    }
  }
  return r ^ mask;



> > This works well, but I need to send 8 characters.
> > I would like it to work without sending codes
> 
> What does 8 characters have to do with UUID? Or the randomness of the UUID? I do not understand what you mean with **sending codes**

**Comment by RobTillaart** [comment] 2022-07-04 18:58
Ok, if you want true randomness you need to harvest random bits aka entropy. 

To get true random bits you need to measure an external random event. In the example the entropy was based upon the arrival time of eight characters.

You are free to measure any other signal to collect your random bits, but you need to be sure you have enough random bits (typical 32 or even 64 for this application). Good sources of random bits have uncertainty or noise. And you should only use the noisy bits.

If your application can access the internet, you should have a look at random.org

**Comment by RobTillaart** [comment] 2022-07-04 18:59
https://www.random.org/clients/http/

**Comment by RobTillaart** [comment] 2022-07-09 08:19
@Rallex 
The problem is about how to properly seed the internal random generators with external randomness.
I have given a few options how to do that and there are many to be found on the internet.
As it is not an internal library problem I close the issue.

**Closed as completed by RobTillaart** 2022-07-09 08:19 UTC
Labels: question
